CREATE DATABASE ACCELOKA;
GO

USE ACCELOKA;
GO

CREATE TABLE Ticket(
    TicketCode UNIQUEIDENTIFIER NOT NULL 
        CONSTRAINT PK_Ticket PRIMARY KEY DEFAULT NEWID(),

    TicketName VARCHAR(255) NOT NULL,
    CategoryName VARCHAR(255) NOT NULL,
    EventDateStart DATETIMEOFFSET NOT NULL,
    Quota INT NOT NULL DEFAULT 0,
    Price DECIMAL(18, 2) NOT NULL,
    PurchaseDate DATETIMEOFFSET NOT NULL 
        CONSTRAINT DF_BookedTicket_PurchaseDate DEFAULT SYSDATETIMEOFFSET(),
    ScheduledDate DATETIMEOFFSET NOT NULL 
        CONSTRAINT DF_BookedTicket_ScheduledDate DEFAULT SYSDATETIMEOFFSET(),

    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    CreatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    UpdatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    UpdatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM'
)
GO


CREATE TABLE BookedTicket(
    BookedTicketId UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_BookedTicket PRIMARY KEY DEFAULT NEWID(),

    TicketCode UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT FK_BookedTicket_Ticket FOREIGN KEY REFERENCES Ticket(TicketCode),

    Quantity INT NOT NULL,
    Price DECIMAL(18, 2) NOT NULL,
    EventDateEnd DATETIMEOFFSET NOT NULL
        CONSTRAINT DF_Ticket_EventDateEnd DEFAULT SYSDATETIMEOFFSET(),

    CreatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    CreatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM',
    UpdatedAt DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(),
    UpdatedBy VARCHAR(255) NOT NULL DEFAULT 'SYSTEM'
)
GO
